- name: set sudo prompt
  ansible.builtin.shell: set-prompt {{component}}

#- name: Import common code
#  ansible.builtin.import_role:
#    name: node_exporter
#    tasks_from: main.yml
#
#- name: Import logstash
#  ansible.builtin.import_role:
#    name: logstash


